//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDatos_API.servicioProductos {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Productos", Namespace="http://schemas.datacontract.org/2004/07/ServicioBroker.Models")]
    [System.SerializableAttribute()]
    public partial class Productos : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PRODUCTOField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PRODUCTO {
            get {
                return this.PRODUCTOField;
            }
            set {
                if ((object.ReferenceEquals(this.PRODUCTOField, value) != true)) {
                    this.PRODUCTOField = value;
                    this.RaisePropertyChanged("PRODUCTO");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="servicioProductos.IProductos", CallbackContract=typeof(BDatos_API.servicioProductos.IProductosCallback))]
    public interface IProductos {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductos/Subscribe", ReplyAction="http://tempuri.org/IProductos/SubscribeResponse")]
        void Subscribe();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductos/Subscribe", ReplyAction="http://tempuri.org/IProductos/SubscribeResponse")]
        System.Threading.Tasks.Task SubscribeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductos/Unsubscribe", ReplyAction="http://tempuri.org/IProductos/UnsubscribeResponse")]
        void Unsubscribe();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductos/Unsubscribe", ReplyAction="http://tempuri.org/IProductos/UnsubscribeResponse")]
        System.Threading.Tasks.Task UnsubscribeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductos/obtenerTodosProductos", ReplyAction="http://tempuri.org/IProductos/obtenerTodosProductosResponse")]
        BDatos_API.servicioProductos.Productos[] obtenerTodosProductos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductos/obtenerTodosProductos", ReplyAction="http://tempuri.org/IProductos/obtenerTodosProductosResponse")]
        System.Threading.Tasks.Task<BDatos_API.servicioProductos.Productos[]> obtenerTodosProductosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductos/IProductos", ReplyAction="http://tempuri.org/IProductos/IProductosResponse")]
        void IProductos(string PRODUCTO, string tipo_Cambio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductos/IProductos", ReplyAction="http://tempuri.org/IProductos/IProductosResponse")]
        System.Threading.Tasks.Task IProductosAsync(string PRODUCTO, string tipo_Cambio);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProductosCallback {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductos/cambiosProductos", ReplyAction="http://tempuri.org/IProductos/cambiosProductosResponse")]
        void cambiosProductos(string PRODUCTO, string tipo_Cambio);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProductosChannel : BDatos_API.servicioProductos.IProductos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductosClient : System.ServiceModel.DuplexClientBase<BDatos_API.servicioProductos.IProductos>, BDatos_API.servicioProductos.IProductos {
        
        public ProductosClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public ProductosClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public ProductosClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ProductosClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ProductosClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void Subscribe() {
            base.Channel.Subscribe();
        }
        
        public System.Threading.Tasks.Task SubscribeAsync() {
            return base.Channel.SubscribeAsync();
        }
        
        public void Unsubscribe() {
            base.Channel.Unsubscribe();
        }
        
        public System.Threading.Tasks.Task UnsubscribeAsync() {
            return base.Channel.UnsubscribeAsync();
        }
        
        public BDatos_API.servicioProductos.Productos[] obtenerTodosProductos() {
            return base.Channel.obtenerTodosProductos();
        }
        
        public System.Threading.Tasks.Task<BDatos_API.servicioProductos.Productos[]> obtenerTodosProductosAsync() {
            return base.Channel.obtenerTodosProductosAsync();
        }
        
        public void IProductos(string PRODUCTO, string tipo_Cambio) {
            base.Channel.IProductos(PRODUCTO, tipo_Cambio);
        }
        
        public System.Threading.Tasks.Task IProductosAsync(string PRODUCTO, string tipo_Cambio) {
            return base.Channel.IProductosAsync(PRODUCTO, tipo_Cambio);
        }
    }
}
